# https://cloud.google.com/functions/docs/testing/test-cicd
steps:

- name: 'docker.io/library/python:3.11'
  entrypoint: /bin/sh
  args: [-c, 'pip install -r requirements.txt']
  dir: 'cd/'

# Delete sum-two-numbers
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'delete', 'function-1', '--gen2', '--region', 'us-central1']

# Deploy sum-two-numbers
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'function-1', '--trigger-http', '--runtime', 'python311', '--entry-point', 'sum-two-numbers', '--allow-unauthenticated', '--gen2', '--region', 'us-central1']
  dir: 'cloud-functions/sum-two-numbers/'

# Delete generate-task
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'delete', 'generate-task', '--gen2', '--region', 'us-central1']

# Deploy generate-task
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'task-generator', '--trigger-http', '--runtime', 'python311', '--entry-point', 'handler', '--allow-unauthenticated', '--gen2', '--region', 'us-central1', '--set-env-vars', 'PROJECT_ID=cloudtasks-374912', 'LOCATION=us-central1', 'QUEUE=test-queue', 'TASK_URL=https://function-1-s5drac3dtq-uc.a.run.app', 'SERVICE_ACCOUNT_EMAIL=task-enqueuer@cloudtasks-374912.iam.gserviceaccount.com']
  dir: 'cloud-functions/generate-task/'

options:
  logging: CLOUD_LOGGING_ONLY